# Netlify configuration for Next.js
[build]
  command = "npm run build"
  publish = ".next"
  
# Handle Next.js routing - for client-side navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For Next.js API routes and Server Components
[functions]
  directory = ".netlify/functions"
  included_files = [".next/server/**"]
