# Netlify configuration for Next.js with Puppeteer
[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "netlify-plugin-chromium"

# Handle Next.js routing - for client-side navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For Next.js API routes and Server Components
[functions]
  directory = ".netlify/functions"
  included_files = [".next/server/**"]
